# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbTKR-AzLYwN63Y3W5OFL9XSqVzGd6BG
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle

!mv kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets list -s leapgestrecog

!kaggle datasets download -d gti-upm/leapgestrecog

!unzip -q leapgestrecog.zip -d dataset/

!ls dataset/leapGestRecog

import os, cv2, random, pandas as pd

src_root = "dataset/leapGestRecog/"
dst_root = "clean_dataset/"
os.makedirs(dst_root, exist_ok=True)

# your final 4-gesture mapping
gesture_map = {
    "01_palm": "open",   # Light ON
    "03_fist": "fist",   # Light OFF
    "05_thumb": "up",    # Brightness increase
    "10_down": "down"    # Brightness decrease
}

IMG_SIZE = (64, 64)
data_rows = []

for subject in sorted(os.listdir(src_root)):        # 00..09
    subj_path = os.path.join(src_root, subject)
    if not os.path.isdir(subj_path): continue
    for gesture in sorted(os.listdir(subj_path)):   # gesture folders
        if gesture not in gesture_map:
            continue
        label = gesture_map[gesture]
        out_dir = os.path.join(dst_root, label)
        os.makedirs(out_dir, exist_ok=True)

        files = os.listdir(os.path.join(subj_path, gesture))
        random.shuffle(files)
        take = files[:300]   # limit to ~300 per gesture

        for f in take:
            in_path = os.path.join(subj_path, gesture, f)
            img = cv2.imread(in_path)
            if img is None:
                continue
            img = cv2.resize(img, IMG_SIZE)
            out_name = f"{subject}_{gesture}_{f}"
            out_path = os.path.join(out_dir, out_name)
            cv2.imwrite(out_path, img)
            data_rows.append({"image_path": out_path, "label": label})

# save the labels to csv
df = pd.DataFrame(data_rows)
df.to_csv("gesture_labels.csv", index=False)
print("Cleaning done! Total images:", len(df))
df.head()

!zip -r clean_dataset.zip clean_dataset/

from google.colab import files
files.download("clean_dataset.zip")
files.download("gesture_labels.csv")